image:
    repository: ghcr.io/mingoo684/cicdex2-frontend
    tag: prod-002
    pullPolicy: IfNotPresent

imagePullSecrets:
    - name: ghcr-pull2

ingress:
    enabled: true
    className: nginx
    host: app.example.com
    path: /
