image:
    repository: 624280434939.dkr.ecr.ap-northeast-2.amazonaws.com/projecta-frontend
    tag: dev-001
    pullPolicy: IfNotPresent

ingress:
    enabled: true
    className: nginx
    host: app.example.com
    path: /
