replicaCount: 1

serviceAccount:
  create: true
  name: ""
  annotations: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80


image:
  repository: ghcr.io/mingoo684/cicdex1-frontend
  tag: "sha-REPLACE_ME"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: nginx
  host: app.local
  path: /
  pathType: Prefix

httpRoute:
  enabled: false


resources: {}
