apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-dev-secrets
  namespace: app-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: api-dev-secrets
    creationPolicy: Owner
  data:
    # All values are sourced from a single AWS secret: app-dev-secrets
    - secretKey: db_password
      remoteRef:
        key: app-dev-secrets
        property: DB_PASSWORD
    - secretKey: jwt_secret_key
      remoteRef:
        key: app-dev-secrets
        property: JWT_SECRET_KEY
