# k8s/env/dev/api-values.yaml

replicaCount: 1

image:
    repository: ghcr.io/mingoo684/cicdex2-api
    tag: dev-007
    pullPolicy: IfNotPresent

# GHCR private/권한 이슈가 있으면 사용
imagePullSecrets:
    - name: ghcr-pull2

env:
    APP_ENV: dev
    DB_HOST: database-1.c7oeqq6c6a58.ap-northeast-2.rds.amazonaws.com
    DB_PORT: "3306"
    DB_NAME: app_db
    DB_USER: app_user
    REDIS_URL: "redis://redis:6379/0"

# Secret을 "파일 마운트"로 주입하는 구조
secretsMount:
    enabled: true
    mountPath: /run/app-secrets
    dbPasswordKey: db_password
    jwtSecretKeyKey: jwt_secret_key

secret:
    enabled: true
    dbPassword: DEV_DB_PASSWORD_CHANGE_ME
    jwtSecretKey: DEV_JWT_CHANGE_ME

probes:
    readinessPath: /health
    livenessPath: /health

resources: {}
    # 필요 시 아래처럼
    # requests:
    #   cpu: "100m"
    #   memory: "256Mi"
    # limits:
    #   cpu: "500m"
    #   memory: "512Mi"

ingress:
    enabled: true
    className: nginx
    host: app.local
    path: /api
